### ISSUE TITLE
Cannot build linksem with OCaml < 4.06.0

### ISSUE THREAD

**Issue by fshaked** [rems-project/linksem#12]
Up until a few days ago everything worked with OCaml 4.02.3, which is the OCaml version supported by rmem.

When I try to build linksem (make LEM=<path_to_lem>) with OCaml 4.02.3 I get this:
[..]
File "byte_sequence_wrapper.ml", line 77, characters 2-11:
Error: Unbound value List.init
[..]

(List.init was introduced in 4.06.0)

Best,
Shaked

**Comment by fshaked** [comment]
Seems like PR #11 will fix that.

**Comment by emersion** [comment]
PR #11 has been merged
